name: Pipeline-frontend

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  lint:
    name: Vue-cli lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Install additional dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
  docker:
    needs: lint
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          file: "Dockerfile"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hubert-miam-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
#  node:
#    needs: [ lint]
#    name: Project tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Use Node.js 20.x
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20.x
#          cache: 'npm'
#      - run: npm install
#      - run: npm run build --if-present
#      - run: npm run test:unit
#      - run: npm run test:e2e
